version: '3.6'
services:
  telegraf:
    image: telegraf:1.25
    container_name: telegraf
    restart: always
    # "995" is the group id of the docker daemon, run: $(stat -c '%g' /var/run/docker.sock)
    # see: https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/
    user: "telegraf:995"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
        max-file: "1"
    ports:
    - '8125:8125'
    depends_on:
      - influxdb
    links:
      - influxdb

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./set-retention.iql:/docker-entrypoint-initdb.d/set-retention.iql
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
        max-file: "1"
    ports:
      - '8086:8086'

  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana-server
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
        max-file: "1"
    ports:
      - '3000:3000'
      
volumes:
  grafana_data: {}
  influxdb_data: {}
